### ISSUE TITLE
到了设定的时间时可以只在当前聚焦的那个vscode窗口弹标签页吗

### ISSUE THREAD

**Issue by syxxmyl** [AS042971/vscode-asoul#3]
RT，开发的时候会打开数个vscode窗口，现在每次到设定时间了就会在所有的窗口都弹出一个新标签页，虽然能多看几眼asoul是好事，但是要在周围同事的目光中多关几次也倍感社死😭😭😭

**Comment by AS042971** [comment]
新推送的版本增加了防社死模式，应该能解决你的问题了

**Comment by syxxmyl** [comment]
防社死模式很好用，谢谢好哥哥
