### ISSUE TITLE
展示提醒页面的时间间隔（分钟）设置为 0 的时候vscode会不断请求导致爆栈

### ISSUE THREAD

**Issue by MarchYuanx** [AS042971/vscode-asoul#8]
## 背景

当 asoul.reminderViewIntervalInMinutes 设置为 0 的时候，vscode 会不间断请求图片 导致爆栈

## 思路

建议 asoul.reminderViewIntervalInMinutes 加上最小值限制，必须大于0

## 跟进

目前的解决方式是手动在 appData/Roaming/Code/User/setting.json 里面修改配置

**Comment by AS042971** [comment]
已解决
